### ISSUE TITLE
hello 可不可以非越狱系统使用呢？

### ISSUE THREAD

**Issue by tanpengsccd** [JyerZ/TiebaVideoAdBlock-iOS#1]
如题

**Comment by JyerZ** [comment]
> 如题

Hello,暂时不可以非越狱环境使用。因为依赖于Cydia的Hook环境。不过要是你有兴趣，可以自己找到贴吧的Mach-O执行文件，利用第三方工具依据我Hook的那部分源码去修改Mach-O中的OC类，除去加载视频广告数据的代码，然后重新打包签名你自己就可以用了（类似于Android中的那种去广告版本的独立apk，直接修改了源代码(smail)，不依赖于任何Hook环境）

**Comment by JyerZ** [comment]
> 如题
